# Generated by Django 4.2.8 on 2025-04-15 11:01

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('user', 'User'), ('notary', 'Notary'), ('admin', 'Administrator')], default='user', max_length=10, verbose_name='role')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=api.models.document_file_path, verbose_name='file')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('custom', 'Custom Document')], default='custom', max_length=15, verbose_name='type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('signed', 'Signed')], default='pending', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='api.document')),
                ('notary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification request',
                'verbose_name_plural': 'verification requests',
            },
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_url', models.CharField(max_length=255, verbose_name='room URL')),
                ('room_id', models.CharField(max_length=100, unique=True, verbose_name='room ID')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='scheduled time')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_session', to='api.verificationrequest')),
            ],
            options={
                'verbose_name': 'video session',
                'verbose_name_plural': 'video sessions',
            },
        ),
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_file', models.FileField(upload_to=api.models.signed_document_file_path, verbose_name='signed file')),
                ('signature_hash', models.CharField(max_length=255, verbose_name='signature hash')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='signed at')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_versions', to='api.document')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signed document',
                'verbose_name_plural': 'signed documents',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/generated_documents/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='finalized')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated document',
                'verbose_name_plural': 'generated documents',
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License')], max_length=15, verbose_name='type')),
                ('document_number', models.CharField(max_length=30, verbose_name='document number')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'identity document',
                'verbose_name_plural': 'identity documents',
                'unique_together': {('user', 'type')},
            },
        ),
    ]
