# Generated by Django 4.2.8 on 2025-04-18 11:43

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='file',
            field=models.FileField(default=None, upload_to=api.models.identity_document_file_path, verbose_name='file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('custom', 'Custom Document')], default='custom', max_length=15, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='NotaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notary_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_notaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
