# Generated by Django 4.2.8 on 2025-04-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_identitydocument_file_alter_document_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaryprofile',
            options={'verbose_name': 'notary profile', 'verbose_name_plural': 'notary profiles'},
        ),
        migrations.AddField(
            model_name='document',
            name='generation_history',
            field=models.JSONField(blank=True, null=True, verbose_name='generation history'),
        ),
        migrations.AddField(
            model_name='document',
            name='generation_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='generation prompt'),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kg', 'Кыргызский')], default='ru', max_length=2, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='api.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='revision_count',
            field=models.IntegerField(default=0, verbose_name='revision count'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'Загружен пользователем'), ('ai_generated', 'Создан с помощью AI'), ('template', 'Создан из шаблона')], default='upload', max_length=20, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('translation', 'Translation'), ('custom', 'Custom Document')], default='custom', max_length=15, verbose_name='type'),
        ),
    ]
