# Generated by Django 4.2.8 on 2025-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_notaryprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finalized at'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='finalized'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('kg', 'Кыргызский')], max_length=2, null=True, verbose_name='source language'),
        ),
        migrations.AddField(
            model_name='document',
            name='translation_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='translation model'),
        ),
        migrations.AddField(
            model_name='document',
            name='translation_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='translation date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'Загружен пользователем'), ('ai_generated', 'Создан с помощью AI'), ('template', 'Создан из шаблона'), ('translation', 'Перевод другого документа')], default='upload', max_length=20, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driver_license', 'Driver License'), ('custom', 'Custom Document')], default='custom', max_length=15, verbose_name='type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source', 'language'], name='api_documen_source_4b487a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source', 'original_document'], name='api_documen_source_7b3c20_idx'),
        ),
    ]
