# Generated by Django 4.2.8 on 2025-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document_finalized_at_document_is_finalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='moderator_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='moderator token'),
        ),
        migrations.AddField(
            model_name='videosession',
            name='participant_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='participant token'),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kg', 'Кыргызский'), ('en', 'English')], default='ru', max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('kg', 'Кыргызский'), ('en', 'English')], max_length=2, null=True, verbose_name='source language'),
        ),
    ]
