version: '3.8'

services:
  backend:
    build: .
    restart: always
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - app-network

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-notary_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-12345}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network: